### ISSUE TITLE
Aux loss decreases and then increases

### ISSUE THREAD

**Issue by eadstry** [LIUZhening111/BiSIC#2]
![image](https://github.com/user-attachments/assets/139fb889-4a89-49d4-a95f-4bc55945ff12)
Firstly, thank you for your meaningful work!
When I tried to reproduce your work, I found that all other metrics were normal, only the aux loss would have the problem of decreasing and then increasing, and after looking at the quantiles I realised that this was due to the quantiles[0] and quantiles[2] being smaller than self.target (quantiles converges to [-5, 0, 5], but self.taiget's value is [-21, 0, 21].).
When you train, do you ever have the same problem? How should I go about getting the aux loss to converge?

**Comment by LIUZhening111** [comment]
Hi, thanks for your interest in our project! 
This aux_loss is used to regularize the majority range of the mass of the distribution, which optimizes towards a target operational region. This function is embedded by [CompressAI](https://interdigitalinc.github.io/CompressAI/), which is actually un-related to the image data or the tasks themselves. And it will not hinder the optimization of our rate-distortion loss.
Your observation of this loss curve is reasonable, common and normal for this training, which is also seen in my own experiments. You can focus on the rate-distortion optimization only. And you can also refer to the link to [CompressAI/aux_loss](https://interdigitalinc.github.io/CompressAI/models.html#compressai.models.CompressionModel.aux_loss) for more information.
Hope this answer helps you.

**Comment by eadstry** [comment]
Thank you for your reply. I noticed that the aux loss you provided for the weights is very low, but I always go down and then up in is experiments. May I ask how you did it? Looking forward to your reply!

**Comment by LIUZhening111** [comment]
I guess more iterations are needed in your experiments. I went to check some of the training samples. Here is a sampled outline of aux_loss curve during training, which goes through ups and downs, while finally leading to a relatively low loss value. Please adjust the hyper-parameters and try training for more steps. 
![image](https://github.com/user-attachments/assets/7da42edd-3d57-4956-8e27-5f2ca8eb23d0)
Hope this helps your training.
